import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import SessionWrapper from "@/app/components/SessionWrapper"; // ✅ Import kiya
=======
import SessionWrapper from "./component/SessionWrapper";
>>>>>>> 2e8e39ec365a9e42612c4ae7cf8ecb7a958c8be0

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jeopardy-Quiz",
  description: "Generated by Sayyad Faizan Ali",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
<<<<<<< HEAD
        <SessionWrapper> {/* ✅ Wrap SessionProvider here */}
            {children}
=======
        <SessionWrapper>
          {children}
>>>>>>> 2e8e39ec365a9e42612c4ae7cf8ecb7a958c8be0
        </SessionWrapper>
      </body>
    </html>
  );
}
